# Generated by Django 5.0.6 on 2024-07-30 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_del_campo', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('forma_productiva', models.CharField(max_length=100)),
                ('cultivar', models.CharField(max_length=100)),
                ('tipo_de_suelo', models.CharField(max_length=100)),
                ('sistema_de_riego', models.CharField(max_length=100)),
                ('altura_snm', models.IntegerField()),
                ('metodo_de_siembra', models.CharField(max_length=100)),
                ('tipo_de_fertilizacion', models.CharField(max_length=100)),
                ('tipo_de_labor_cultural', models.CharField(max_length=100)),
                ('distancia_de_siembra', models.FloatField()),
            ],
            options={
                'ordering': ['municipio'],
            },
        ),
    ]
