# Generated by Django 5.0.6 on 2024-08-06 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datosmaiz', '0002_observacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campo',
            options={'ordering': ['municipio', 'nombre_del_campo']},
        ),
        migrations.AddField(
            model_name='observacion',
            name='campo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='datosmaiz.campo'),
        ),
    ]
