# Generated by Django 5.0.6 on 2024-08-26 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datosmaiz', '0003_alter_campo_options_observacion_campo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('municipio', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['municipio', 'codigo'],
            },
        ),
        migrations.AlterField(
            model_name='campo',
            name='nombre_del_campo',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('temperatura_maxima', models.FloatField()),
                ('temperatura_minima', models.FloatField()),
                ('temperatura_media', models.FloatField()),
                ('humedad_maxima', models.FloatField()),
                ('humedad_minima', models.FloatField()),
                ('humedad_media', models.FloatField()),
                ('horas_hr_mayor_que_90', models.FloatField()),
                ('hr_mayor_que_90_max', models.FloatField()),
                ('hr_mayor_que_90_min', models.FloatField()),
                ('hr_mayor_que_90_med', models.FloatField()),
                ('precipitacion', models.FloatField()),
                ('velocidad_del_viento', models.FloatField()),
                ('estacion', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='datosmaiz.estacion')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('denominacion_del_cultivar', models.CharField(max_length=100)),
                ('tipo_de_suelo', models.CharField(max_length=100)),
                ('fecha_de_siembra', models.DateField()),
                ('semilla_con_tratamiento_quimico', models.BooleanField()),
                ('area_sembrada', models.FloatField()),
                ('tipo_de_fertilizante', models.CharField(max_length=100)),
                ('dosis_de_fertilizante', models.FloatField()),
                ('marco_de_siembra', models.FloatField()),
                ('sistema_de_riego', models.CharField(max_length=100)),
                ('estacion', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='datosmaiz.estacion')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pronostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacion_del_cultivar', models.CharField(max_length=100)),
                ('periodo_favorable', models.IntegerField()),
                ('plazo_primeros_sintomas', models.IntegerField()),
                ('tipo_de_mensaje', models.CharField(max_length=100)),
                ('total_grados_dias', models.FloatField()),
                ('fase_fenologica', models.IntegerField()),
                ('unidad', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='datosmaiz.unidad')),
            ],
            options={
                'ordering': ['unidad'],
            },
        ),
    ]
