# Generated by Django 5.0.6 on 2024-09-17 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datosmaiz', '0006_remove_pronostico_fase_fenologica_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pronostico',
            name='dias_criticos',
        ),
        migrations.AddField(
            model_name='pronostico',
            name='fecha_de_siembra',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='unidad',
            name='dias_criticos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pronostico',
            name='periodo_favorable',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pronostico',
            name='plazo_primeros_sintomas',
            field=models.CharField(max_length=100),
        ),
    ]
