# Generated by Django 5.0.6 on 2024-10-03 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datosmaiz', '0007_remove_pronostico_dias_criticos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registro',
            options={'ordering': ['-fecha']},
        ),
    ]
