# Generated by Django 5.0.6 on 2024-10-18 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datosmaiz', '0008_alter_registro_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pronostico',
            unique_together={('unidad', 'fecha_de_siembra', 'denominacion_del_cultivar', 'tipo_de_mensaje')},
        ),
    ]
