# Generated by Django 5.0.6 on 2024-10-30 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datosmaiz', '0009_alter_pronostico_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pronostico',
            options={'ordering': ['-fecha_de_siembra']},
        ),
    ]
